### ISSUE TITLE
Success Rate?

### ISSUE THREAD

**Issue by rprashantsingh** [tulitpal/tulit-sap-fortify#2]
For a given run, how do we compute the success rate of this monitor?
Does the result file have enough data to track such aspects?

**Comment by tulitpal** [comment]
I interpreted the question in two ways and I will try to answer both.

- _Determining the success rate of the monitoring tool:_
> If somehow, the monitoring tool encounters an error, we can count that as a fail from the end of the monitoring tool because we cannot determine whether fortify is up and running or down in these cases. Also, the rate at which the monitoring tool hits the application-state-controller would determine the level of control. For example, one call every 5 minutes would give a finer level of control as compared to, say, one call every 10 minutes.

- _Determining the uptime to downtime ratio of fortify:_
> This can simply be calculated using the total success calls where 'maintenanceMode' was false and the failure calls where 'maintenanceMode' was true giving us an idea on how many calls the service was down out of the total calls made.

Data for both of these scenarios are received by the monitoring tool and can be achieved with very minimal additional coding.
